version: 2.1
jobs:
  build:
    machine: true
    steps:
      - run:
          command: |
            sudo apt-get update -qq && sudo apt-get install -y libaio1 libevent-dev
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository ppa:rpardini/adoptopenjdk -y
            sudo apt-get update -qq
            sudo apt install adoptopenjdk-8-installer -y
            sudo apt-get install -y maven git
            echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
            sudo apt-get update -qq
            sudo apt-get install sbt
          no_output_timeout: 30m
      - checkout
      - restore_cache:
          key: scala-library-dependencies-{{ checksum "build.sbt" }}
      - run:
          command: git fetch --tags
      - run:
          command: sbt clean +test scalafmtCheck
          no_output_timeout: 1h
      - run:
          command: sbt ci-release
      - save_cache:
          paths: [ "~/.sbt/boot", "~/.ivy2/cache", "~/.cache/coursier",  "~/.wixMySQL" ]
          key: scala-library-dependencies-{{ checksum "build.sbt" }}

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /v.*/
