name: Bump Version
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  bump-version:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
        persist-credentials: false
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.4
      with:
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        default_bump: patch
    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        preset: 'angular'
        git-user-name: j5ik2o
        git-user-email: j5ik2o@gmail.com
        tag-prefix: 'v'
        output-file: "false"
    - name: Create a GitHub release
      uses: actions/create-release@v1
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        tag_name: ${{ steps.changelog.outputs.tag }}
        release_name: Release ${{ steps.changelog.outputs.tag }}
        body: ${{ steps.changelog.outputs.clean_changelog }}

