name: Bump version
on:
  workflow_dispatch
jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - run: |
        git clone https://github.com/markchalloner/git-semver.git /tmp && sudo /tmp/git-semver/install.sh
        git semver patch
        git push origin $(git semver get)
#    - name: Bump version and push tag
#      uses: anothrNick/github-tag-action@1.26.0
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        WITH_V: true
#        DEFAULT_BUMP: patch
#        RELEASE_BRANCHES: main
