name: Bump version
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
        persist-credentials: false
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#    - name: git setting
#      run: |
#        git config --local user.email "j5ik2o@gmail.com"
#        git config --local user.name "j5ik2o"
#    - name: git current version
#      id: current-version
#      env:
#        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#      run: |
#        VER=$(git describe --abbrev=0)
#        echo "VER=${VER}"
#        echo "::set-output name=value::${VER}"
#    - name: next version
#      uses: j5ik2o/semver-control-action@v1.0.3
#      id: get-next-version
#      with:
#        current-version: ${{ steps.current-version.outputs.value }}
#    - name: git tag and push
#      env:
#        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#      run: |
#        echo "version = ${{ steps.get-next-version.outputs.version }}"
#        git tag v${{ steps.get-next-version.outputs.version }} -m "v${{ steps.get-next-version.outputs.version }}"
#        git push origin v${{ steps.get-next-version.outputs.version }}
#    - name: Create a GitHub release
#      uses: actions/create-release@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#      with:
#        tag_name: v${{ steps.get-next-version.outputs.version }}
#        release_name: Release v${{ steps.get-next-version.outputs.version }}
#        body: v${{ steps.get-next-version.outputs.version }}
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.4
      with:
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: Create a GitHub release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
