name: Bump Version
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  bump-version:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
        persist-credentials: false
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.4
      with:
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        default_bump: patch
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        check-latest: true
    - run: cat ./package.json
    - run: npm version ${{ steps.tag_version.outputs.new_tag }}
    - run: cat ./package.json
    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        output-file: "CHANGELOG.md"
        git-user-name: j5ik2o
        git-user-email: j5ik2o@gmail.com
        git-message: 'chore(release): {version}'
        preset: 'angular'
        tag-prefix: 'v'
        skip-version-file: true
        skip-commit: true
        skip-on-empty: true
        version-file: 'package.json'
    - name: Create a GitHub release
      uses: actions/create-release@v1
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.changelog.outputs.clean_changelog }}

